In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
df = pd.read_csv('../Datasets/house-price-interval/dataset.csv')
test = pd.read_csv('../Datasets/house-price-interval/test.csv')

df.head()

,id,sale_date,sale_price,sale_nbr,sale_warning,join_status,join_year,latitude,longitude,area,...,view_olympics,view_cascades,view_territorial,view_skyline,view_sound,view_lakewash,view_lakesamm,view_otherwater,view_other,submarket
0,0,2014-11-15,236000,2.0,,nochg,2025,47.2917,-122.3658,53,...,0,0,0,0,0,0,0,0,0,I
1,1,1999-01-15,313300,NaN,26,nochg,2025,47.6531,-122.1996,74,...,0,0,0,0,0,1,0,0,0,Q
2,2,2006-08-15,341000,1.0,,nochg,2025,47.4733,-122.1901,30,...,0,0,0,0,0,0,0,0,0,K
3,3,1999-12-15,267000,1.0,,nochg,2025,47.4739,-122.3295,96,...,0,0,0,0,0,0,0,0,0,G
4,4,2018-07-15,1650000,2.0,,miss99,2025,47.7516,-122.1222,36,...,0,0,0,0,0,0,0,0,0,P

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 47 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                200000 non-null  int64
 1   sale_date         200000 non-null  object
 2   sale_price        200000 non-null  int64
 3   sale_nbr          157818 non-null  float64
 4   sale_warning      200000 non-null  object
 5   join_status       200000 non-null  object
 6   join_year         200000 non-null  int64
 7   latitude          200000 non-null  float64
 8   longitude         200000 non-null  float64
 9   area              200000 non-null  int64
 10  city              200000 non-null  object
 11  zoning            200000 non-null  object
 12  subdivision       182450 non-null  object
 13  present_use       200000 non-null  int64
 14  land_val          200000 non-null  int64
 15  imp_val           200000 non-null  int64
 16  year_built        200000 non-null  int64
 17  year_reno         200000 non-null  int64
 18  sqft_lot          200000 non-null  int64
 19  sqft              200000 non-null  int64
 20  sqft_1            200000 non-null  int64
 21  sqft_fbsmt        200000 non-null  int64
 22  grade             200000 non-null  int64
 23  fbsmt_grade       200000 non-null  int64
 24  condition         200000 non-null  int64
 25  stories           200000 non-null  float64
 26  beds              200000 non-null  int64
 27  bath_full         200000 non-null  int64
 28  bath_3qtr         200000 non-null  int64
 29  bath_half         200000 non-null  int64
 30  garb_sqft         200000 non-null  int64
 31  gara_sqft         200000 non-null  int64
 32  wfnt              200000 non-null  int64
 33  golf              200000 non-null  int64
 34  greenbelt         200000 non-null  int64
 35  noise_traffic     200000 non-null  int64
 36  view_rainier      200000 non-null  int64
 37  view_olympics     200000 non-null  int64
 38  view_cascades     200000 non-null  int64
 39  view_territorial  200000 non-null  int64
 40  view_skyline      200000 non-null  int64
 41  view_sound        200000 non-null  int64
 42  view_lakewash     200000 non-null  int64
 43  view_lakesamm     200000 non-null  int64
 44  view_otherwater   200000 non-null  int64
 45  view_other        200000 non-null  int64
 46  submarket         198283 non-null  object
dtypes: float64(4), int64(36), object(7)
memory usage: 71.7+ MB

In [29]:
df.describe()

,id,sale_price,sale_nbr,join_year,latitude,longitude,area,present_use,land_val,imp_val,...,view_rainier,view_olympics,view_cascades,view_territorial,view_skyline,view_sound,view_lakewash,view_lakesamm,view_otherwater,view_other
count,200000.000000,2.000000e+05,157818.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,2.000000e+05,2.000000e+05,...,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,99999.500000,5.841495e+05,2.162599,2023.403600,47.549248,-122.210416,48.644215,4.108860,4.601691e+05,4.917715e+05,...,0.017940,0.053985,0.058800,0.215550,0.018425,0.055565,0.050075,0.014090,0.020875,0.013455
std,57735.171256,4.170595e+05,1.113090,6.241643,0.142710,0.140339,27.132002,7.199323,3.510444e+05,3.680505e+05,...,0.218994,0.379119,0.381868,0.724224,0.222746,0.380011,0.353664,0.200154,0.248977,0.181147
min,0.000000,5.029300e+04,1.000000,1999.000000,47.155200,-122.527700,1.000000,2.000000,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,49999.750000,3.050000e+05,1.000000,2025.000000,47.446500,-122.323800,26.000000,2.000000,2.310000e+05,2.800000e+05,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,99999.500000,4.599500e+05,2.000000,2025.000000,47.562800,-122.222700,48.000000,2.000000,3.770000e+05,4.090000e+05,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,149999.250000,7.249500e+05,3.000000,2025.000000,47.673500,-122.121700,71.000000,2.000000,5.940000e+05,5.990000e+05,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,199999.000000,2.999950e+06,11.000000,2025.000000,47.777800,-121.161300,100.000000,29.000000,1.386400e+07,1.006700e+07,...,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000

In [30]:
df.isnull().sum().sort_values(ascending=False)

sale_nbr            42182
subdivision         17550
submarket            1717
sale_price              0
sale_warning            0
join_status             0
sale_date               0
join_year               0
latitude                0
area                    0
longitude               0
city                    0
zoning                  0
present_use             0
id                      0
land_val                0
imp_val                 0
year_reno               0
year_built              0
sqft                    0
sqft_1                  0
sqft_fbsmt              0
sqft_lot                0
fbsmt_grade             0
condition               0
stories                 0
beds                    0
bath_full               0
bath_3qtr               0
bath_half               0
grade                   0
garb_sqft               0
gara_sqft               0
golf                    0
wfnt                    0
noise_traffic           0
view_rainier            0
view_olympics           0
greenbelt               0
view_cascades           0
view_territorial        0
view_sound              0
view_skyline            0
view_lakewash           0
view_lakesamm           0
view_otherwater         0
view_other              0
dtype: int64

In [31]:
df.drop(columns=['sale_nbr','subdivision','submarket'],inplace=True)
test.drop(columns=['sale_nbr','subdivision','submarket'],inplace=True)

In [32]:
nums = df.select_dtypes(include=['int64', 'float64'])
nums

,id,sale_price,join_year,latitude,longitude,area,present_use,land_val,imp_val,year_built,...,view_rainier,view_olympics,view_cascades,view_territorial,view_skyline,view_sound,view_lakewash,view_lakesamm,view_otherwater,view_other
0,0,236000,2025,47.2917,-122.3658,53,2,167000,372000,1975,...,0,0,0,0,0,0,0,0,0,0
1,1,313300,2025,47.6531,-122.1996,74,2,1184000,598000,1962,...,0,0,0,0,0,0,1,0,0,0
2,2,341000,2025,47.4733,-122.1901,30,2,230000,356000,1986,...,0,0,0,0,0,0,0,0,0,0
3,3,267000,2025,47.4739,-122.3295,96,2,190000,518000,1998,...,0,0,0,0,0,0,0,0,0,0
4,4,1650000,2025,47.7516,-122.1222,36,2,616000,1917000,1998,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,199995,277500,2025,47.5503,-122.0285,69,2,521000,620000,1977,...,0,0,0,0,0,0,0,0,0,0
199996,199996,1296000,2025,47.6789,-122.1164,72,2,667000,1107000,2008,...,0,0,0,0,0,0,0,0,0,0
199997,199997,845000,2025,47.6939,-122.3542,6,29,225000,492000,2017,...,0,0,0,0,0,0,0,0,0,0
199998,199998,890000,2025,47.6433,-122.0613,35,2,554000,617000,1981,...,0,0,0,0,0,0,0,0,0,0
199999,199999,799000,2025,47.5806,-122.3881,48,29,268000,455000,2023,...,0,0,0,0,0,0,0,0,0,0

In [33]:
for i in nums.columns:
    print(i,end=", ")

id, sale_price, join_year, latitude, longitude, area, present_use, land_val, imp_val, year_built, year_reno, sqft_lot, sqft, sqft_1, sqft_fbsmt, grade, fbsmt_grade, condition, stories, beds, bath_full, bath_3qtr, bath_half, garb_sqft, gara_sqft, wfnt, golf, greenbelt, noise_traffic, view_rainier, view_olympics, view_cascades, view_territorial, view_skyline, view_sound, view_lakewash, view_lakesamm, view_otherwater, view_other,

In [34]:
features = ['sale_price','latitude','area','land_val','imp_val','year_built','sqft','condition','stories','beds','gara_sqft']
df = df[features]
df.head()

,sale_price,latitude,area,land_val,imp_val,year_built,sqft,condition,stories,beds,gara_sqft
0,236000,47.2917,53,167000,372000,1975,1560,5,1.0,3,500
1,313300,47.6531,74,1184000,598000,1962,2040,4,1.0,3,0
2,341000,47.4733,30,230000,356000,1986,1640,3,2.0,3,480
3,267000,47.4739,96,190000,518000,1998,2610,3,2.0,4,530
4,1650000,47.7516,36,616000,1917000,1998,4040,3,2.0,4,810

In [35]:
test_features = ['latitude','area','land_val','imp_val','year_built','sqft','condition','stories','beds','gara_sqft']

test = test[test_features]

In [36]:
X = df.drop('sale_price',axis=1)
y = df['sale_price']

In [37]:
X

,latitude,area,land_val,imp_val,year_built,sqft,condition,stories,beds,gara_sqft
0,47.2917,53,167000,372000,1975,1560,5,1.0,3,500
1,47.6531,74,1184000,598000,1962,2040,4,1.0,3,0
2,47.4733,30,230000,356000,1986,1640,3,2.0,3,480
3,47.4739,96,190000,518000,1998,2610,3,2.0,4,530
4,47.7516,36,616000,1917000,1998,4040,3,2.0,4,810
...,...,...,...,...,...,...,...,...,...,...
199995,47.5503,69,521000,620000,1977,1870,4,1.0,3,0
199996,47.6789,72,667000,1107000,2008,3340,3,2.0,4,0
199997,47.6939,6,225000,492000,2017,1690,3,3.0,3,0
199998,47.6433,35,554000,617000,1981,2080,4,2.0,3,550
199999,47.5806,48,268000,455000,2023,1320,3,3.0,3,0

In [38]:
from xgboost import XGBRegressor
model = XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=4)

In [39]:
model.fit(X,y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=4, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=100, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [40]:
y_pred = model.predict(test)